# Generated by Django 4.2.4 on 2023-08-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clientquery_review_delete_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='serviceimg/')),
            ],
        ),
    ]
