# Generated by Django 4.2.7 on 2023-11-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_imagemodel_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
