# Generated by Django 4.2.7 on 2023-11-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_imageresize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageResize',
            new_name='ResizableImage',
        ),
        migrations.RenameField(
            model_name='resizableimage',
            old_name='image',
            new_name='original_image',
        ),
    ]
