# Generated by Django 4.2.7 on 2023-11-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_resizedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resizedimage',
            name='image',
            field=models.ImageField(upload_to='resize/'),
        ),
    ]
