# Generated by Django 4.2.7 on 2023-11-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_resizedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertpngModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='covertpng/')),
            ],
        ),
    ]
