# Generated by Django 4.2.7 on 2023-11-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_convertpngmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertjpgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='convertjpg/')),
            ],
        ),
    ]
