# Generated by Django 4.2.7 on 2023-12-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_convertjpgmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
