# Generated by Django 3.2.12 on 2026-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_service_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
